"use strict";
/**
 * models/Activity.js
 * ─────────────────────────────────────────────────────────────
 * Mongoose schema for a fully-saved Activity document.
 *
 * When are Activity docs created?
 *   - When a user saves an AI-generated recommendation to their
 *     personal collection (Step 5 — dashboardController).
 *   - Activities are stored globally (not per-user) so they can
 *     be referenced across users. User.savedActivities stores
 *     a lightweight snapshot + a reference to this _id.
 *
 * Distinction from ActivitySnapshot (in User.js):
 *   - ActivitySnapshot  → embedded, always available, for fast rendering
 *   - Activity doc      → full record, source of truth, for search/filter
 * ─────────────────────────────────────────────────────────────
 */
const mongoose = require("mongoose");

const { Schema } = mongoose;

// ── Category constants (shared with frontend filters) ────────────────────────
const CATEGORIES = [
  "Creative",
  "Outdoor",
  "Gaming",
  "Fitness",
  "Music",
  "Reading",
  "Travel",
  "Food & Cooking",
  "Movies & Shows",
  "Social",
  "Mindfulness",
  "Learning",
  "DIY & Crafts",
  "Photography",
  "General",
];

// ── Activity schema ──────────────────────────────────────────────────────────
const ActivitySchema = new Schema(
  {
    // ── Core content ───────────────────────────────────────
    title: {
      type     : String,
      required : [true, "Activity title is required"],
      trim     : true,
      maxlength: [120, "Title cannot exceed 120 characters"],
    },

    description: {
      type     : String,
      required : [true, "Description is required"],
      trim     : true,
      maxlength: [1000, "Description cannot exceed 1000 characters"],
    },

    category: {
      type   : String,
      enum   : CATEGORIES,
      default: "General",
    },

    // ── Time & Cost ────────────────────────────────────────
    estimatedTime: {
      type   : String,
      default: "",
      // Human-readable, e.g. "30 minutes", "1–2 hours", "Half day"
    },

    estimatedCost: {
      type   : String,
      default: "Free",
      // Human-readable, e.g. "Free", "₹100–₹300", "Under ₹500"
    },

    // Numeric versions for range-based filters
    minCostINR: { type: Number, default: 0 },
    maxCostINR: { type: Number, default: 0 },

    // ── Location & Type ────────────────────────────────────
    locationType: {
      type   : String,
      enum   : ["indoor", "outdoor", "both", "online"],
      default: "both",
    },

    // Physical location tag, if applicable (e.g. "Mumbai", "Delhi", "Any")
    locationTag: {
      type   : String,
      default: "Any",
      trim   : true,
    },

    // ── Media ──────────────────────────────────────────────
    imageUrl: {
      type   : String,
      default: "",
      // Cloudinary secure_url or a generated placeholder
    },

    imagePublicId: {
      type   : String,
      default: "",
      // Cloudinary public_id — needed to delete/replace the image
    },

    // ── AI generation metadata ─────────────────────────────
    isAiGenerated: {
      type   : Boolean,
      default: true,
      // true  → generated by Gemini
      // false → manually added by admin
    },

    aiPromptUsed: {
      type   : String,
      default: "",
      // Store the exact prompt that produced this activity (for debugging / analytics)
    },

    // ── Engagement ─────────────────────────────────────────
    saveCount: {
      type   : Number,
      default: 0,
      min    : 0,
      // Incremented each time any user saves this activity
    },

    tags: {
      type   : [String],
      default: [],
      // e.g. ["solo", "cheap", "creative", "weekend"]
    },
  },
  {
    timestamps: true,   // createdAt + updatedAt
  }
);

// ────────────────────────────────────────────────────────────
//  VIRTUALS
// ────────────────────────────────────────────────────────────

/**
 * isFree — true when maxCostINR is 0 (or estimatedCost is "Free")
 */
ActivitySchema.virtual("isFree").get(function () {
  return this.maxCostINR === 0 || this.estimatedCost.toLowerCase() === "free";
});

/**
 * placeholderImage — returns imageUrl or a deterministic Unsplash topic image
 */
ActivitySchema.virtual("placeholderImage").get(function () {
  if (this.imageUrl) return this.imageUrl;
  // Deterministic Unsplash image seeded by title slug
  const seed = encodeURIComponent(this.title.toLowerCase().replace(/\s+/g, "-"));
  return `https://source.unsplash.com/600x400/?${seed}`;
});

// ────────────────────────────────────────────────────────────
//  INDEXES — optimise common query patterns
// ────────────────────────────────────────────────────────────
ActivitySchema.index({ category: 1 });
ActivitySchema.index({ locationType: 1 });
ActivitySchema.index({ saveCount: -1 });          // "Most saved" sort
ActivitySchema.index({ tags: 1 });
ActivitySchema.index({ title: "text", description: "text", tags: "text" }); // full-text search

// ────────────────────────────────────────────────────────────
//  STATIC METHODS
// ────────────────────────────────────────────────────────────

/**
 * Activity.findByCategory(cat) — convenience wrapper
 */
ActivitySchema.statics.findByCategory = function (category) {
  return this.find({ category }).sort({ saveCount: -1 });
};

/**
 * Activity.findTrending(limit) — top saved activities
 */
ActivitySchema.statics.findTrending = function (limit = 6) {
  return this.find().sort({ saveCount: -1 }).limit(limit);
};

// ────────────────────────────────────────────────────────────
//  JSON transform
// ────────────────────────────────────────────────────────────
ActivitySchema.set("toJSON", {
  virtuals: true,
  transform(doc, ret) {
    delete ret.__v;
    return ret;
  },
});

ActivitySchema.set("toObject", { virtuals: true });

// Export both the model and the CATEGORIES list (used in forms/validation)
const Activity = mongoose.model("Activity", ActivitySchema);

module.exports = Activity;
module.exports.CATEGORIES = CATEGORIES;
